# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foia',
            name='ack_date',
            field=models.DateField(verbose_name='date acknowledgement letter received'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='appeal_date',
            field=models.DateField(verbose_name='date appeal filed'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='filed_date',
            field=models.DateField(verbose_name='date filed'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='resp_date',
            field=models.DateField(verbose_name='date response received'),
        ),
    ]
