# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0004_auto_20170217_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanbeing',
            name='is_clerk',
            field=models.BooleanField(default=False, verbose_name='Is this person the clerk in charge of FOIAs?'),
        ),
        migrations.AddField(
            model_name='humanbeing',
            name='is_lawyer',
            field=models.BooleanField(default=False, verbose_name='Is this person a lawyer?'),
        ),
    ]
