# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0005_auto_20170221_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='foia',
            name='lawsuit_filed',
            field=models.BooleanField(default=False, verbose_name='Have you (or the lawyers) filed a lawsuit this?'),
        ),
        migrations.AddField(
            model_name='foia',
            name='lawsuit_filed_date',
            field=models.DateField(blank=True, null=True, verbose_name='date lawsuit filed'),
        ),
        migrations.AddField(
            model_name='foia',
            name='lawsuit_notes',
            field=models.TextField(blank=True, verbose_name='Notes about the lawsuit '),
        ),
        migrations.AddField(
            model_name='foia',
            name='request_subject',
            field=models.TextField(blank=True, null=True, verbose_name='what was the request for?'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='appealed',
            field=models.BooleanField(default=False, verbose_name='Have you (or the lawyers) appealed this?'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='received_ack_letter',
            field=models.BooleanField(default=False, verbose_name='Have you received an acknowledgement yet?'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='response_notes',
            field=models.TextField(blank=True, verbose_name='Notes about your response. (complain about the redactions here!) '),
        ),
    ]
