# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foias', '0006_auto_20170221_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanbeing',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foia',
            name='lawsuit_filed',
            field=models.BooleanField(default=False, verbose_name='Have you (or the lawyers) filed a lawsuit over this?'),
        ),
    ]
