# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0007_auto_20170222_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanbeing',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
