# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0009_auto_20170222_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foia',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
