# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0015_auto_20170227_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='NytEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clerk', models.BooleanField(default=False, verbose_name='Is this person a clerk, I mean, news assistant?')),
                ('is_lawyer', models.BooleanField(default=False, verbose_name='Got a jay dee?')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foias.MyUser')),
            ],
        ),
    ]
