# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0018_auto_20170227_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes about the agency'),
        ),
    ]
