# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0019_auto_20170227_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nytemployee',
            options={'verbose_name': 'Clerk or Lawyer', 'verbose_name_plural': 'Clerks and Lawyers'},
        ),
        migrations.AlterField(
            model_name='foia',
            name='date_response_due_custom',
            field=models.DateField(blank=True, null=True, verbose_name="When are the records due? If the agency didn't give you a specific date, leave this blank and I'll calculate the statutory deadline."),
        ),
    ]
