# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0020_auto_20170228_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='foia',
            name='response_satisfactory',
            field=models.BooleanField(default=False, verbose_name="We're satisfied with what we got and do not need to appeal, sue or pursue this any further."),
        ),
    ]
