# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0023_auto_20170310_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foia',
            name='is_state_foia',
            field=models.BooleanField(default=False, help_text="This app doesn't know about the FOIA deadlines in those places, so you won't get notifications for these, but you're welcome to track it here.", verbose_name='Is this a FOIA filed with a state or a foreign country?'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='request_notes',
            field=models.TextField(blank=True, help_text='Did you send by mail or email? Why did you phrase it the way you did?', verbose_name='Request text and/or notes'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='response_notes',
            field=models.TextField(blank=True, help_text='Complain about the redactions here!', verbose_name='Notes about your response.'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='response_url',
            field=models.TextField(blank=True, help_text='Google Drive and Dropbox are both good places to store documents and both generate shareable links you could paste here.', verbose_name="Link to the documents and/or response letter. (Optional. Skip this if you're storing the documents on paper or offline)"),
        ),
        migrations.AlterField(
            model_name='foia',
            name='submission_notes',
            field=models.TextField(blank=True, help_text="Record your phone call updates here. Did they respond by mail or email? Do you have a phone number? Did they tell you what track it's on?", verbose_name='notes about the process'),
        ),
    ]
