# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0024_auto_20170420_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NytEmployee',
            new_name='SpecialPerson',
        ),
        migrations.AlterField(
            model_name='foia',
            name='appealed',
            field=models.BooleanField(default=False, verbose_name='Have you (or your lawyer) appealed this?'),
        ),
        migrations.AlterField(
            model_name='foia',
            name='lawsuit_filed',
            field=models.BooleanField(default=False, verbose_name='Have you (or your lawyer) filed a lawsuit over this?'),
        ),
    ]
