# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0025_auto_20170518_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tag Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes about this tag')),
            ],
        ),
        migrations.AddField(
            model_name='foia',
            name='tags',
            field=models.ManyToManyField(to='foias.Tag'),
        ),
        migrations.AddField(
            model_name='specialperson',
            name='default_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foias.Tag'),
        ),
    ]
