# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0026_auto_20170607_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialperson',
            options={'verbose_name': 'People (Special Roles, Default Projects, etc.)', 'verbose_name_plural': 'People (Special Roles, Default Projects, etc.)'},
        ),
        migrations.AlterField(
            model_name='foia',
            name='tags',
            field=models.ManyToManyField(to='foias.Tag', verbose_name='What project(s) is this request a part of?'),
        ),
    ]
