# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0028_auto_20170609_1656'),
        ('foias', '0028_auto_20170612_1253'),
    ]

    operations = [
    ]
