# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0029_merge_20170621_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialperson',
            name='slack_handle',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name=b'Slack Name'),
        ),
    ]
