# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foias', '0030_specialperson_slack_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialperson',
            name='default_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foias.Tag'),
        ),
    ]
